### ISSUE TITLE
cmake script should build blosc_plugin.so

### ISSUE THREAD

**Issue by stevengj** [Blosc/hdf5-blosc#3]
Currently, the `cmake` script only builds the `blosc_filter` library; it should also build the `blosc_plugin` shared library.

**Comment by dswanepoel** [comment]
Would it be feasible to simply compile `blosc_plugin.c` into `blosc_filter.so` so the library can be used as a dynamically loaded plugin as well? This works for me, although it does require a symlink to the library from `HDF5_PLUGIN_PATH` (or a copy installed there).

**Comment by stevengj** [comment]
@dswanepoel, I think it would be a lot easier to use if you just linked everything (`blosc_plugin.c` and `libblosc`) into a single `blosc_filter.so` file.   Inter-library dependences are tricky to manage, especially on Windows, and disk space is cheap.

**Comment by dswanepoel** [comment]
@stevengj, I agree. Currently `libblosc_filter.so` is dynamically linked to the locally compiled `libblosc.so.1`, which is not ideal.

**Comment by FrancescAlted** [comment]
Sorry being late into this, but I am trying to get hdf5-blosc in a better shape, specially after C-Blosc 1.8 series fixing some serious long-standing issues (see #7 for example).  @stevengj I like your modifications to the README, an I wonder if you would you like to contribute cmake improvements in order to compile the plugin too?  And I also think that it makes sense to produce a single shared library for it.

**Comment by FrancescAlted** [comment]
Fixed in #15
